version: "3.9"

services:
  postgres:
    image: postgres
    container_name: bank_db
    expose:
      - "5435"
    command: -p 5435
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=bank
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bank_api
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_NAME=bank
      - DB_PORT=5435
      - DB_HOST=bank_db