database:
  host: localhost
  port: 5432
  dialect: postgres
  user: root
  dbname: bank
  password: secret
  gormMaxIdleConn: 20
  gormMaxOpenConn: 300
  gormMaxConnLifetimeHour: 1
  ssl_mode: disable
  schema: public.

app:
  host: localhost
  port: 8080


token:
  symmetric_key: "12345678901234567890123456789012"
  access_token_duration: 15m
  authorization_header_key: "authorization"
  authorization_type_bearer: "bearer"
  authorization_payload_key: "authorization_payload"