app:
  host: localhost
  port: 8001

token:
  symmetric_key: "12345678901234567890123456789012"
  access_token_duration: 15m
  authorization_header_key: "authorization"
  authorization_type_bearer: "bearer"
  authorization_payload_key: "authorization_payload"