basePath: /api/v1
definitions:
  account.AccountOutput:
    properties:
      balance:
        type: integer
      currency:
        type: string
      id:
        type: integer
      owner:
        type: string
    type: object
  account.CreateAccountInput:
    properties:
      balance:
        type: integer
      currency:
        enum:
        - AZN
        - USD
        type: string
      owner:
        type: string
    required:
    - balance
    type: object
  errors.Response:
    properties:
      key:
        type: string
      message:
        type: string
    type: object
host: localhost:8001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Sample App API
  version: "2.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page Size
        in: query
        name: page_size
        type: integer
      - description: Page ID
        in: query
        name: page_id
        type: integer
      - description: Bearer
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/account.AccountOutput'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Get accounts
      tags:
      - Account
    post:
      consumes:
      - application/json
      parameters:
      - description: account
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/account.AccountOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Create a new account.
      tags:
      - Account
  /accounts/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bearer
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.AccountOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Get a account by ID.
      tags:
      - Account
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
