basePath: /api/v1
definitions:
  account.AccountOutput:
    properties:
      balance:
        type: integer
      currency:
        type: string
      id:
        type: integer
      owner:
        type: string
    type: object
  account.CreateAccountInput:
    properties:
      balance:
        type: integer
      currency:
        type: string
      owner:
        type: string
    required:
    - balance
    - currency
    type: object
  account.TransferInput:
    properties:
      amount:
        type: integer
      currency:
        type: string
      from_account_id:
        type: integer
      to_account_id:
        type: integer
    type: object
  db.Account:
    properties:
      balance:
        type: integer
      created_at:
        type: string
      currency:
        type: string
      id:
        type: integer
      owner:
        type: string
    type: object
  db.Entry:
    properties:
      account_id:
        type: integer
      amount:
        type: integer
      created_at:
        type: string
      id:
        type: integer
    type: object
  db.Transfer:
    properties:
      amount:
        type: integer
      created_at:
        type: string
      from_account_id:
        type: integer
      id:
        type: integer
      to_account_id:
        type: integer
    type: object
  db.TransferTxResult:
    properties:
      from_account:
        $ref: '#/definitions/db.Account'
      from_entry:
        $ref: '#/definitions/db.Entry'
      to_account:
        $ref: '#/definitions/db.Account'
      to_entry:
        $ref: '#/definitions/db.Entry'
      transfer:
        $ref: '#/definitions/db.Transfer'
    type: object
  errors.Response:
    properties:
      key:
        type: string
      message:
        type: string
    type: object
  user.CreateUserInput:
    properties:
      email:
        type: string
      full_name:
        type: string
      password:
        type: string
      username:
        type: string
    required:
    - email
    - full_name
    - password
    - username
    type: object
  user.LoginUserInput:
    properties:
      password:
        type: string
      username:
        type: string
    required:
    - password
    - username
    type: object
  user.LoginUserOutput:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/user.UserDto'
    type: object
  user.UserDto:
    properties:
      email:
        type: string
      full_name:
        type: string
      username:
        type: string
    type: object
host: localhost:8001
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Sample App API
  version: "2.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      parameters:
      - description: Page Size
        in: query
        name: page_size
        type: integer
      - description: Page ID
        in: query
        name: page_id
        type: integer
      - description: Bearer
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/account.AccountOutput'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Get accounts
      tags:
      - Account
    post:
      consumes:
      - application/json
      parameters:
      - description: account
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/account.CreateAccountInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/account.AccountOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Create a new account.
      tags:
      - Account
  /accounts/{id}:
    get:
      consumes:
      - application/json
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      - description: Bearer
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.AccountOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Get a account by ID.
      tags:
      - Account
  /login:
    post:
      consumes:
      - application/json
      parameters:
      - description: Login data
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.LoginUserInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/user.LoginUserOutput'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Login a user.
      tags:
      - User
  /transfer:
    post:
      consumes:
      - application/json
      parameters:
      - description: transfer
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/account.TransferInput'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/db.TransferTxResult'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Transfer money between 2 accounts
      tags:
      - Account
  /users:
    post:
      consumes:
      - application/json
      parameters:
      - description: User
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/user.CreateUserInput'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/user.UserDto'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/errors.Response'
      summary: Create a new User.
      tags:
      - User
schemes:
- http
- https
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
